mem:
  big_mem_avail: FALSE
  normal_mem_per_core_gb: 4
  big_mem_per_core_gb: 26
tmp_dir: tmp
raws:
  Contigs: "__PROJ_DIR__/__ASSEMBLY__"
  Alignment_metagenomics: "__PROJ_DIR__/__ASSEMBLY_MAP__"
  Contig_depth: ""
sample: "__PREFIX_____SAMPLE__"
outputdir: "__OUT_DIR__"
db_path: "/mnt/lscratch/users/ohickl/binning/tools/binny_alpha_006_20210624/database"
binning:
  binny:
    kmers: '2,3,4'
    cutoff: 1000
  filtering:
    completeness: 80
    purity: 85

