mem:
  big_mem_avail: TRUE
  normal_mem_per_core_gb: 8
  big_mem_per_core_gb: 36
tmp_dir: tmp
raws:
  Contigs: "test/assembly.fasta"
  Alignment_metagenomics: "test/mg.reads.sorted.bam"
  Contig_depth: ""
sample: test
outputdir: "test_output"
db_path: "database"
binning:
  binny:
    kmers: '2,3,4' # Input a list, e.g. '2,3,4'
    cutoff: 1000
  filtering:
    completeness: 80
    purity: 85
