binning:
  binny:
    cutoff: 1000
    kmers: 2,3,4
  filtering:
    completeness: 70
    purity: 90
db_path: database
mem:
  big_mem_avail: false
  big_mem_per_core_gb: 26
  normal_mem_per_core_gb: 4
outputdir: binny_initialized
raws:
  Alignment_metagenomics: test/mg.reads.sorted.bam
  Contig_depth: ''
  Contigs: test/assembly.fasta
sample: test
tmp_dir: tmp
